<?php

declare(strict_types=1);
$toolchain=$argv[1]??'';require $toolchain.'/vendor/autoload.php';require $toolchain.'/src/gen_stub.php';require $toolchain.'/src/Build/TargetInternalClassMetadata.php';
use TypePhp\Build\TargetInternalClassMetadata;use TypePhp\Resolver\Reflection as TargetReflection;
function targetClassCheck(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);echo 'PASS '.$message.PHP_EOL;}
$start=microtime(true);$sdk=$toolchain.'/vendor/swoole/phpx/full-static/sdk';$nm=dirname($toolchain,2).'/llvm/bin/llvm-nm';$root=sys_get_temp_dir().'/webman-aot-target-internal-'.bin2hex(random_bytes(6));mkdir($root,0700,true);
try{
$selected=TargetInternalClassMetadata::read($sdk,$nm);targetClassCheck(isset($selected['classes']['redis'])&&count($selected['classes']['redis']['methods'])===260,'selected SDK complete Redis declaration matches actual archive');$warm=TargetInternalClassMetadata::read($sdk,$nm);targetClassCheck($warm['sha256']===$selected['sha256']&&array_keys($warm['classes'])===array_keys($selected['classes']),'warm selected identity stable');
// Use the actual target module and startup registry in small owned archives.
$members=[];$stream=fopen($sdk.'/lib/libphp.a','rb');targetClassCheck(fread($stream,8)==="!<arch>\n",'selected GNU archive identity');$strings='';while(($header=fread($stream,60))!==''){$length=(int)trim(substr($header,48,10));$name=trim(substr($header,0,16));$offset=ftell($stream);if($name==='//')$strings=fread($stream,$length);else{$name=str_starts_with($name,'/')&&ctype_digit(substr($name,1))?explode("/\n",substr($strings,(int)substr($name,1)),2)[0]:rtrim($name,'/');if(in_array($name,['redis.o','internal_functions_cli.o'],true))$members[$name][]=fread($stream,$length);}fseek($stream,$offset+$length+($length%2));}fclose($stream);targetClassCheck(count($members['redis.o']??[])===2&&count($members['internal_functions_cli.o']??[])===1,'actual duplicate member names retained for module identity selection');
$fixture=$root.'/sdk';foreach(['lib','include/php/ext/redis','include/php/main','include/php/Zend']as$path)mkdir($fixture.'/'.$path,0700,true);foreach(['sdk-manifest.json','include/php/main/php_config.h','include/php/Zend/zend_API.h','include/php/Zend/zend_compile.h','include/php/Zend/zend_types.h','include/php/Zend/zend_type_info.h']as$path)copy($sdk.'/'.$path,$fixture.'/'.$path);foreach(glob($sdk.'/include/php/ext/redis/*.h')as$path)copy($path,$fixture.'/include/php/ext/redis/'.basename($path));
$writeArchive=function(array $objects)use($fixture):void{$bytes="!<arch>\n";$strings='';$offsets=[];foreach($objects as[$name,$object])if(strlen($name)>15&&!isset($offsets[$name])){$offsets[$name]=strlen($strings);$strings.=$name."/\n";}if($strings!==''){$bytes.=str_pad('//',16).str_repeat(' ',32).str_pad((string)strlen($strings),10)."`\n".$strings.(strlen($strings)%2?"\n":'');}foreach($objects as[$name,$object]){$name=isset($offsets[$name])?'/'.$offsets[$name]:$name.'/';$bytes.=str_pad($name,16).str_pad('0',12).str_pad('0',6).str_pad('0',6).str_pad('100644',8).str_pad((string)strlen($object),10)."`\n".$object.(strlen($object)%2?"\n":'');}file_put_contents($fixture.'/lib/libphp.a',$bytes);};$objects=[['redis.o',$members['redis.o'][0]],['redis.o',$members['redis.o'][1]],['internal_functions_cli.o',$members['internal_functions_cli.o'][0]]];$writeArchive($objects);$normal=TargetInternalClassMetadata::read($fixture,$nm);targetClassCheck(isset($normal['classes']['redis']),'real module entry selects correct same-name member');
$header=$fixture.'/include/php/ext/redis/redis_arginfo.h';$source=file_get_contents($header);$checkNoClass=function(string $name)use($fixture,$nm):void{targetClassCheck(!isset(TargetInternalClassMetadata::read($fixture,$nm)['classes']['redis']),$name);};
foreach(['known type mismatch'=>str_replace('ZEND_ARG_TYPE_INFO(0, host, IS_STRING, 0)','ZEND_ARG_TYPE_INFO(0, host, IS_LONG, 0)',$source),'conditional class flags with unrelated same text'=>str_replace('class_entry = zend_register_internal_class_ex(&ce, NULL);',"class_entry = zend_register_internal_class_ex(&ce, NULL);\n#if UNKNOWN_TARGET_FLAG\nclass_entry->ce_flags |= ZEND_ACC_FINAL;\n#endif",$source)."\nstatic void unrelated_flags(zend_class_entry *class_entry) {\nclass_entry->ce_flags |= ZEND_ACC_FINAL;\n}\n",'conditional method registration'=>str_replace('ZEND_ME(Redis, scan, arginfo_class_Redis_scan, ZEND_ACC_PUBLIC)',"#if UNKNOWN_TARGET_CONDITION\nZEND_ME(Redis, scan, arginfo_class_Redis_scan, ZEND_ACC_PUBLIC)\n#endif",$source),'default literal mismatch'=>str_replace('"6379"','"6380"',$source),'duplicate matching header'=>$source]as$name=>$changed){$path=$name==='duplicate matching header'?$fixture.'/include/php/ext/redis/duplicate_arginfo.h':$header;file_put_contents($path,$changed);$checkNoClass($name);if($path!==$header)unlink($path);file_put_contents($header,$source);}
$blob=$objects[1][1];$u64=fn(string $b,int $o)=>unpack('P',substr($b,$o,8))[1];$u32=fn(string $b,int $o)=>unpack('V',substr($b,$o,4))[1];$u16=fn(string $b,int $o)=>unpack('v',substr($b,$o,2))[1];$shoff=$u64($blob,40);$count=$u16($blob,60);$namesIndex=$u16($blob,62);$namesOffset=$u64($blob,$shoff+$namesIndex*64+24);$dataIndex=null;$dataOffset=null;for($i=0;$i<$count;++$i){$at=$shoff+$i*64;$nameOffset=$namesOffset+$u32($blob,$at);$name=explode("\0",substr($blob,$nameOffset),2)[0];if($name==='.data.rel.ro'){$dataIndex=$i;$dataOffset=$u64($blob,$at+24);}}targetClassCheck($dataIndex!==null,'actual declaration section for terminal counterexample');$relocated=null;for($i=0;$i<$count;++$i){$at=$shoff+$i*64;if($u32($blob,$at+4)!==4||$u32($blob,$at+44)!==$dataIndex)continue;$off=$u64($blob,$at+24);$size=$u64($blob,$at+32);$relas=substr($blob,$off,$size);$first=null;for($j=0;$j<$size;$j+=24)if($u64($relas,$j)===0){$first=substr($relas,$j,24);break;}targetClassCheck($first!==null,'real first method name relocation');$sentinel=count($normal['classes']['redis']['methods'])*48;$extra=pack('P',$sentinel).substr($first,8);$relocated=$blob.$relas.$extra;$relocated=substr_replace($relocated,pack('P',strlen($blob)),$at+24,8);$relocated=substr_replace($relocated,pack('P',$size+24),$at+32,8);break;}$bad=$objects;$bad[1][1]=$relocated;$writeArchive($bad);$checkNoClass('raw zero terminal carrying relocation is not FE_END');$bad=$objects;$bad[1][1]=substr_replace($blob,"\x01",$dataOffset+count($normal['classes']['redis']['methods'])*48,1);$writeArchive($bad);$checkNoClass('nonzero terminal record rejected');$bad=$objects;$bad[1][1]=substr_replace($bad[1][1],"\x02\0",16,2);$writeArchive($bad);$checkNoClass('ET_EXEC cannot supply target declarations');$bad=$objects;$bad[1][1]=substr_replace($bad[1][1],"\x02",5,1);$writeArchive($bad);$checkNoClass('foreign byte order rejected');$bad=$objects;$bad[1][1]=substr_replace($bad[1][1],"\xb7\0",18,2);$writeArchive($bad);$checkNoClass('foreign machine rejected');$bad=$objects;$bad[1][1]=substr($bad[1][1],0,100);$writeArchive($bad);$checkNoClass('truncated ELF rejected');$bad=$objects;$bad[]=$objects[1];$writeArchive($bad);$checkNoClass('duplicate module object rejects ambiguity');$writeArchive($objects);$config=$fixture.'/include/php/Zend/zend_types.h';$layout=file_get_contents($config);file_put_contents($config,str_replace('#define IS_LONG', '#define OTHER_LONG',$layout));$checkNoClass('record declaration identity drift rejected');file_put_contents($config,$layout);
$restored=TargetInternalClassMetadata::read($fixture,$nm);targetClassCheck(isset($restored['classes']['redis'])&&$restored['sha256']===$normal['sha256'],'restored metadata and content cache identity');targetClassCheck(TargetInternalClassMetadata::read(null,$nm)['classes']===[]&&TargetInternalClassMetadata::read($fixture,null)['classes']===[],'absent SDK or target reader preserves original boundary');
final class TargetInternalCompiler extends TypePhp\CompilerTest{public function __construct(string $root){parent::__construct($root);$this->forTest=true;$this->setBuildDir($root.'/build');}public function argument(string $class,string $method,int $index){return $this->getAotCallArgInfo($method,$class,$index);}public function constructor(string $class){return $this->findConstructor($class);}}
$compile=function(string $source,string $name)use($root,$fixture,$nm){$dir=$root.'/'.$name;mkdir($dir);$file=$dir.'/fixture.php';file_put_contents($file,$source);$compiler=new TargetInternalCompiler($dir);TargetReflection::setTargetInternalClasses($fixture,$nm);$compiler->prepareFile($file);$compiler->convertFile($file);return[$compiler,file_get_contents($compiler->getCppFile($file))];};
[$compiler,$cpp]=$compile('<?php class TargetRedisChild extends Redis {public function connect(string $host,int $port=6379,float $timeout=0,?string $persistent_id=null,int $retry_interval=0,float $read_timeout=0,?array $context=null):bool{return true;}public function probe(mixed &$iterator):mixed{return $this->scan($iterator);}}','compatible');targetClassCheck($compiler->argument('TargetRedisChild','scan',0)?->byRef===true&&str_contains($cpp,'php::VarList{&iterator}'),'target inherited scan preserves Zend reference carrier');targetClassCheck(($compiler->constructor('TargetRedisChild')['className']??null)==='Redis','target constructor identified without host class');targetClassCheck(!TargetReflection::getClass('Redis')&&TargetReflection::isInternalClass('Redis')&&!TargetReflection::isInternalClass('MissingTargetClass'),'target internal identity distinct from source and unknown classes');
foreach(['byref'=>'public function scan(mixed $iterator,?string $pattern=null,int $count=0,?string $type=null):array|false{return false;}','contravariance'=>'public function connect(int $host,int $port=6379,float $timeout=0,?string $persistent_id=null,int $retry_interval=0,float $read_timeout=0,?array $context=null):bool{return true;}','covariance'=>'public function auth(mixed $credentials):int{return 1;}']as$name=>$method){try{$compile('<?php class InvalidRedisChild extends Redis {'.$method.'}',$name);throw new RuntimeException($name.' incorrectly accepted');}catch(TypePhp\Exception\TestError$e){targetClassCheck(str_contains($e->getMessage(),'must be compatible'),'actual target LSP rejects '.$name);}}
echo'PASS target internal class metadata/frontend elapsed='.round(microtime(true)-$start,3)."s\n";
}finally{$entries=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($entries as$entry)$entry->isDir()?rmdir($entry->getPathname()):unlink($entry->getPathname());rmdir($root);}
